[package]
name = "wass"
version = "0.1.0"
authors = ["baadjis <baadjisidy@gmail>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
